### ISSUE TITLE
Python 2.6 doesn't provide 'ssl.create_default_context'

### ISSUE THREAD

**Issue by nhinds** [rabbitmq/rabbitmq-management#225]
Running `rabbitmqadmin` on Python 2.6 fails with an error "AttributeError: 'module' object has no attribute 'create_default_context'". This is broken on master and on 3.6.2, but works on 3.6.1.

```
  File "/usr/local/bin/rabbitmqadmin", line 991, in <module>
    main()
  File "/usr/local/bin/rabbitmqadmin", line 413, in main
    method()
  File "/usr/local/bin/rabbitmqadmin", line 607, in invoke_declare
    self.put(uri, json.dumps(upload))
  File "/usr/local/bin/rabbitmqadmin", line 439, in put
    return self.http("PUT", "%s/api%s" % (self.options.path_prefix, path), body)
  File "/usr/local/bin/rabbitmqadmin", line 449, in http
    ssl_ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
AttributeError: 'module' object has no attribute 'create_default_context'
```

According to [the rabbitmqadmin documentation](https://www.rabbitmq.com/management-cli.html) and the version check at the top of the `rabbitmqadmin` file, Python 2.6 is the minimum version of Python supported, but [ssl.create_default_context was added in 2.7.9](https://docs.python.org/2/library/ssl.html).

I'm not sure if this is a documentation issue (in which case the HTML page and the version check would need to be updated) or a bug in `rabbitmqadmin`'s compatibility introduced in #149.

**Comment by nhinds** [comment]
On second thought: this is 100% a bug, not a documentation issue, at least for 3.6.2. A bump in the patch version should not require a bump in the minor version of dependencies.

**Comment by michaelklishin** [comment]
If we can find a reasonable way to do the same thing on 2.6, so be it. Otherwise HTTPS is a lot more important than Python 2.6.

**Comment by nhinds** [comment]
Requiring a new minor version in a patch version is completely ignoring semantic versioning. Why not revert #149 on the release version? It seemed to just replace the "deprecated" code path (which worked for HTTPS) with a python 2.7 way

**Comment by michaelklishin** [comment]
Except that HTTPS did not actually work before with rabbitmqadmin in the common case when RabbitMQ and the tool used certificates signed by the same CA
without explicitly trusting each other's certificate.

**Comment by nhinds** [comment]
Okay, didn't see anything about that in #149, must have been the other issues referenced in that commit. How about a version check or feature detection, falling back on the older method if running under python 2.6?

It would allow python 2.7 users to handle that case, and let python 2.6 continue to work in the scenarios it did before

**Comment by michaelklishin** [comment]
The plan is to investigate how we can initialize the same context on 2.6.

**Comment by michaelklishin** [comment]
OK, so that we have at least some data points: what OS and version still ships with Python 2.6? Even Ubuntu 12.04 [provides 2.7.3](http://packages.ubuntu.com/search?keywords=python) as far as I can tell.

I understand that there are ways to test this with Virtualenv but our small team cannot afford to support versions that are hardly in use at the moment. This is the first time this compatibility issue is reported.

**Comment by nhinds** [comment]
Hmm, I thought I encountered it with python 2.6 on trusty (14.04.1) but a fresh installation of that shows the image I'm using ships with python 2.7.6. Sorry for the version confusion, I listed 2.6 because that was the minimum requirement on the rabbitmq documentation.

I've just reproduced this on a fresh 14.04.1 installation, and can confirm that the errors in my original issue description occur on Python 2.7.6.

Since `ssl.create_default_context` was added in 2.7.9, I guess the issue can be renamed "Python <=2.7.8 doesn't provide 'ssl.create_default_context'"?

**Comment by michaelklishin** [comment]
So Python prior to `2.7.9` doesn't seem to have a `SSLContext` abstraction at all:
```
AttributeError: 'module' object has no attribute 'SSLContext'
```

A workaround seems to be [to use a 3rd party library](https://github.com/kennethreitz/requests/issues/2495). `rabbitmqadmin` doesn't have external dependencies and we'd *really* like to keep it that way.

**Comment by michaelklishin** [comment]
In addition, from [Python 2.7 docs](https://docs.python.org/2/library/httplib.html):

```
(as of 2.7.9):

This class now performs all the necessary certificate and hostname checks by default. To revert to the previous, unverified, behavior ssl._create_unverified_context() can be passed to the context parameter.
```

So HTTPS support in the standard library prior to `2.7.9` is pretty objectively broken and limited. The best we can do is supporting HTTPS without peer verification (enabled on `2.7.9+` by default).

**Comment by michaelklishin** [comment]
Next thing about Python 2.6-2.7.8: SSLv3 is enabled by default, while RabbitMQ listeners in recent versions disable it by default. Some users [develop wget wrappers to work around](https://github.com/twoolie/NBT/issues/78), others [override standard library classes](http://anotherlayer.net/2014/10/16/forcing-tls1-in-pythons-urllib2-on-osx/).

**Comment by michaelklishin** [comment]
[rabbitmqadmin docs](https://www.rabbitmq.com/management-cli.html) are updated to require `2.7.9` when HTTPS is used. That doc page didn't even list Python 3 as supported, which means it was quite a bit out of date.

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-management/pull/228 fixes this to the extent that we have the resources and interest in supporting older Python versions.

This can be further improved by switching to `urllib2` and disabling SSLv3 via a custom handler but this is too much for a point release. If someone cares enough about older Python versions to do that work, we'd consider a pull request for `.3.7.0` (so, against the master branch).

**Comment by amine187** [comment]
i have Python version 2.7.12 installed but i still have the same issue !!

**Comment by lukebakken** [comment]
@amine187 Python `2.7.12` is over [two years old](https://legacy.python.org/dev/peps/pep-0373/). If this is an issue in the latest `2.7.X` release, let us know.

**Comment by michaelklishin** [comment]
Modern `2.7.x` versions do have an [ssl.create_default_context](https://docs.python.org/2/library/ssl.html#context-creation).

This is not a Python discussion forum and without knowing how Python was installed we cannot suggest much (e.g. TLS modules can be missing entirely).
